export const environment = {
  production: false,
  oauthToken: "Bearer BQD5srsU5Zf6dVBWfI0bvZ6dAYZHvnODvDfyoZVl_mipk5gKiPDSyhrVGVppoZ5npwXydnvsXwVQQGNtG0H-yDNSiI3inMBTpxtS-M5RD9sDrN-ZR_FE6P85voaXWZnrJvrW0MB4vxWz2F_RIx67QvZG023tHdEbIX3xGI_xz-3IkvrB8ZoDVwYkVQhZsOXCWpM"
};